"""export-bundle command — bundle all build artefacts into one folder."""

from __future__ import annotations

import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path

import click


@click.command("export-bundle")
@click.option("--video-file", "-v", required=True,
              help="Path to the rendered video file (.mp4).")
@click.option("--output-dir", "-o", default="bundle", show_default=True,
              help="Destination folder for the bundle.")
@click.option("--thumbnail-file", "-t", default=None,
              help="Path to a thumbnail image (.jpg/.png).")
@click.option("--social-json", "-j", default=None,
              help="Path to a social pack JSON (generated by social-pack command).")
@click.option("--config-file", default=None,
              help="Config JSON to snapshot into the bundle.")
@click.option("--profile-file", default=None,
              help="Brand profile JSON to snapshot into the bundle.")
@click.option("--render-summary", default=None,
              help="Render summary JSON to include (from --save-summary).")
@click.option("--script-file", "-s", default=None,
              help="Original script file to include in the bundle.")
@click.option("--platform", "-p", default="reels",
              type=click.Choice(["reels", "tiktok", "youtube-shorts", "youtube", "landscape"]),
              help="Platform (used when auto-generating social pack).")
@click.option("--brand-name", "-b", default="",
              help="Brand name (used when auto-generating social pack).")
@click.option("--force", is_flag=True, default=False,
              help="Overwrite an existing bundle directory.")
@click.option("--publish-manifest", "publish_manifest_file", default=None,
              help="Publish manifest JSON to include in the bundle.")
@click.option("--add-to-queue", default=None,
              help="Path to an existing publish queue to add a manifest to after bundling.")
def export_bundle(
    video_file: str,
    output_dir: str,
    thumbnail_file: str | None,
    social_json: str | None,
    config_file: str | None,
    profile_file: str | None,
    render_summary: str | None,
    script_file: str | None,
    platform: str,
    brand_name: str,
    force: bool,
    publish_manifest_file: str | None,
    add_to_queue: str | None,
) -> None:
    """Bundle video, thumbnail, social pack, and config into one folder.

    Creates a ready-to-share export with all related files in one place.
    A manifest.json is written listing every included file with metadata.

    Examples:

      # Minimal — just the video
      clipforge export-bundle --video-file output/video.mp4

      # Full bundle
      clipforge export-bundle --video-file output/video.mp4 \\
          --thumbnail-file output/thumb.jpg \\
          --social-json output/social.json \\
          --config-file config.json \\
          --output-dir bundle/episode-1
    """
    import os

    from clipforge.utils import save_json

    if not os.path.exists(video_file):
        click.echo(f"  Error: Video file not found: {video_file}", err=True)
        sys.exit(1)

    out_path = Path(output_dir)
    if out_path.exists() and any(out_path.iterdir()):
        if not force:
            click.echo(
                f"  Bundle directory already exists and is not empty: {output_dir}\n"
                f"  Use --force to overwrite.",
                err=True,
            )
            sys.exit(1)
    out_path.mkdir(parents=True, exist_ok=True)

    manifest: dict = {
        "created_at": datetime.now(timezone.utc).isoformat(),
        "platform": platform,
        "brand_name": brand_name,
        "files": [],
    }
    bundle_files: list[dict] = []

    def _add(src: str, label: str, dest_name: str | None = None) -> str:
        """Copy src to bundle and record in manifest."""
        src_path = Path(src)
        dest_file = out_path / (dest_name or src_path.name)
        shutil.copy2(src, dest_file)
        size = dest_file.stat().st_size
        entry = {"label": label, "file": dest_file.name, "size_bytes": size}
        bundle_files.append(entry)
        return str(dest_file)

    # ── Video ─────────────────────────────────────────────────────────
    video_dest = _add(video_file, "video")
    click.echo(f"  [video]     {Path(video_dest).name}")

    # ── Thumbnail ─────────────────────────────────────────────────────
    if thumbnail_file and os.path.exists(thumbnail_file):
        thumb_dest = _add(thumbnail_file, "thumbnail")
        click.echo(f"  [thumb]     {Path(thumb_dest).name}")
    else:
        click.echo("  [thumb]     (not provided)")

    # ── Script ────────────────────────────────────────────────────────
    if script_file and os.path.exists(script_file):
        _add(script_file, "script", dest_name="script.txt")
        click.echo("  [script]    script.txt")

    # ── Social pack ───────────────────────────────────────────────────
    if social_json and os.path.exists(social_json):
        _add(social_json, "social_json", dest_name="social_pack.json")
        click.echo("  [social]    social_pack.json  (copied)")
        # Also write TXT alongside it
        import json as _json
        pack = _json.loads(Path(social_json).read_text(encoding="utf-8"))
        _write_social_txt(pack, out_path / "social_pack.txt")
        bundle_files.append({"label": "social_txt", "file": "social_pack.txt"})
        click.echo("  [social]    social_pack.txt   (generated)")
    else:
        # Auto-generate from video filename stem
        click.echo("  [social]    (auto-generating from video name...)")
        from clipforge.social_pack import generate_social_pack
        stem = Path(video_file).stem.replace("-", " ").replace("_", " ")
        pack = generate_social_pack(stem, platform=platform, brand_name=brand_name)
        sj = out_path / "social_pack.json"
        st = out_path / "social_pack.txt"
        save_json(pack, sj)
        _write_social_txt(pack, st)
        for label, fn in [("social_json", sj.name), ("social_txt", st.name)]:
            bundle_files.append({"label": label, "file": fn})
        click.echo("  [social]    social_pack.json + social_pack.txt")

    # ── Render summary ────────────────────────────────────────────────
    if render_summary and os.path.exists(render_summary):
        _add(render_summary, "render_summary", dest_name="render_summary.json")
        click.echo("  [summary]   render_summary.json")

    # ── Config snapshot ───────────────────────────────────────────────
    if config_file and os.path.exists(config_file):
        _add(config_file, "config_snapshot", dest_name="config_snapshot.json")
        click.echo("  [config]    config_snapshot.json")

    # ── Profile snapshot ──────────────────────────────────────────────
    if profile_file and os.path.exists(profile_file):
        _add(profile_file, "profile_snapshot", dest_name="profile_snapshot.json")
        click.echo("  [profile]   profile_snapshot.json")

    # ── Publish manifest ──────────────────────────────────────────────
    if publish_manifest_file and os.path.exists(publish_manifest_file):
        _add(publish_manifest_file, "publish_manifest",
             dest_name="publish_manifest.json")
        click.echo("  [manifest]  publish_manifest.json  (copied)")
    else:
        # Auto-generate a minimal publish manifest from what we know
        from clipforge.publish_manifest import PublishManifest
        # Try to read social data already written to the bundle
        _sp_path = out_path / "social_pack.json"
        _title = ""
        _caption = ""
        _hashtags = ""
        _cta = ""
        _hook = ""
        if _sp_path.exists():
            import json as _json2
            _pack = _json2.loads(_sp_path.read_text(encoding="utf-8"))
            _title = _pack.get("title", "")
            _caption = _pack.get("caption", "")
            _hashtags = _pack.get("hashtags", "")
            _cta = _pack.get("cta", "")
            _hook = _pack.get("hook", "")
        pm = PublishManifest(
            job_name=Path(video_file).stem,
            platform=platform,
            video_path=str(Path(video_file).resolve()),
            thumbnail_path=(
                str(Path(thumbnail_file).resolve())
                if thumbnail_file and os.path.exists(thumbnail_file)
                else ""
            ),
            bundle_dir=str(out_path.resolve()),
            title=_title,
            caption=_caption,
            hashtags=_hashtags,
            cta=_cta,
            hook=_hook,
            brand_name=brand_name,
            status="draft",
        )
        _pm_path = out_path / "publish_manifest.json"
        pm.save(_pm_path)
        bundle_files.append({"label": "publish_manifest", "file": _pm_path.name})
        click.echo("  [manifest]  publish_manifest.json  (generated)")

    # ── Bundle manifest ────────────────────────────────────────────────
    manifest["files"] = bundle_files
    manifest["total_files"] = len(bundle_files)
    save_json(manifest, out_path / "manifest.json")

    total_kb = sum(
        (out_path / f["file"]).stat().st_size
        for f in bundle_files
        if (out_path / f["file"]).exists()
    ) // 1024

    click.echo()
    click.echo(f"  Bundle complete: {len(bundle_files)} file(s) → {output_dir}/")
    click.echo(f"  Total size     : ~{total_kb} KB")
    click.echo()

    # ── Add to queue if requested ──────────────────────────────────────
    if add_to_queue:
        from clipforge.publish_manifest import PublishManifest
        from clipforge.publish_queue import PublishQueue
        try:
            q = PublishQueue.load(add_to_queue)
            pm_file = out_path / "publish_manifest.json"
            if pm_file.exists():
                loaded_pm = PublishManifest.load(pm_file)
                q.append(loaded_pm)
                click.echo(f"  Added to queue : {add_to_queue}")
                click.echo(f"  Queue total    : {len(q)} item(s)")
                click.echo()
        except (FileNotFoundError, ValueError) as exc:
            click.echo(f"  Warning: Could not add to queue: {exc}", err=True)


def _write_social_txt(pack: dict, path: Path) -> None:
    """Write social pack to a plain-text file."""
    lines = [
        f"Platform : {pack.get('platform', '')}",
        f"Brand    : {pack.get('brand_name', '')}",
        "",
        "TITLE",
        pack.get("title", ""),
        "",
        "HOOK",
        pack.get("hook", ""),
        "",
        "CTA",
        pack.get("cta", ""),
        "",
        "HASHTAGS",
        pack.get("hashtags", ""),
        "",
        "CAPTION",
        "-------",
        pack.get("caption", ""),
    ]
    path.write_text("\n".join(lines), encoding="utf-8")
